var countrySelect = "";
countrySelect+= '<select name="countries">';
	countrySelect+= '<option value="AF">Afghanistan</option>';
	countrySelect+= '<option value="AX">Åland Islands</option>';
	countrySelect+= '<option value="AL">Albania</option>';
	countrySelect+= '<option value="DZ">Algeria</option>';
	countrySelect+= '<option value="AS">American Samoa</option>';
	countrySelect+= '<option value="AD">Andorra</option>';
	countrySelect+= '<option value="AO">Angola</option>';
	countrySelect+= '<option value="AI">Anguilla</option>';
	countrySelect+= '<option value="AQ">Antarctica</option>';
	countrySelect+= '<option value="AG">Antigua and Barbuda</option>';
	countrySelect+= '<option value="AR">Argentina</option>';
	countrySelect+= '<option value="AM">Armenia</option>';
	countrySelect+= '<option value="AW">Aruba</option>';
	countrySelect+= '<option value="AU">Australia</option>';
	countrySelect+= '<option value="AT">Austria</option>';
	countrySelect+= '<option value="AZ">Azerbaijan</option>';
	countrySelect+= '<option value="BS">Bahamas</option>';
	countrySelect+= '<option value="BH">Bahrain</option>';
	countrySelect+= '<option value="BD">Bangladesh</option>';
	countrySelect+= '<option value="BB">Barbados</option>';
	countrySelect+= '<option value="BY">Belarus</option>';
	countrySelect+= '<option value="BE">Belgium</option>';
	countrySelect+= '<option value="BZ">Belize</option>';
	countrySelect+= '<option value="BJ">Benin</option>';
	countrySelect+= '<option value="BM">Bermuda</option>';
	countrySelect+= '<option value="BT">Bhutan</option>';
	countrySelect+= '<option value="BO">Bolivia, Plurinational State of</option>';
	countrySelect+= '<option value="BQ">Bonaire, Sint Eustatius and Saba</option>';
	countrySelect+= '<option value="BA">Bosnia and Herzegovina</option>';
	countrySelect+= '<option value="BW">Botswana</option>';
	countrySelect+= '<option value="BV">Bouvet Island</option>';
	countrySelect+= '<option value="BR">Brazil</option>';
	countrySelect+= '<option value="IO">British Indian Ocean Territory</option>';
	countrySelect+= '<option value="BN">Brunei Darussalam</option>';
	countrySelect+= '<option value="BG">Bulgaria</option>';
	countrySelect+= '<option value="BF">Burkina Faso</option>';
	countrySelect+= '<option value="BI">Burundi</option>';
	countrySelect+= '<option value="KH">Cambodia</option>';
	countrySelect+= '<option value="CM">Cameroon</option>';
	countrySelect+= '<option value="CA">Canada</option>';
	countrySelect+= '<option value="CV">Cape Verde</option>';
	countrySelect+= '<option value="KY">Cayman Islands</option>';
	countrySelect+= '<option value="CF">Central African Republic</option>';
	countrySelect+= '<option value="TD">Chad</option>';
	countrySelect+= '<option value="CL">Chile</option>';
	countrySelect+= '<option value="CN">China</option>';
	countrySelect+= '<option value="CX">Christmas Island</option>';
	countrySelect+= '<option value="CC">Cocos (Keeling) Islands</option>';
	countrySelect+= '<option value="CO">Colombia</option>';
	countrySelect+= '<option value="KM">Comoros</option>';
	countrySelect+= '<option value="CG">Congo</option>';
	countrySelect+= '<option value="CD">Congo, the Democratic Republic of the</option>';
	countrySelect+= '<option value="CK">Cook Islands</option>';
	countrySelect+= '<option value="CR">Costa Rica</option>';
	countrySelect+= '<option value="CI">Côte d\'Ivoire</option>';
	countrySelect+= '<option value="HR">Croatia</option>';
	countrySelect+= '<option value="CU">Cuba</option>';
	countrySelect+= '<option value="CW">Curaçao</option>';
	countrySelect+= '<option value="CY">Cyprus</option>';
	countrySelect+= '<option value="CZ">Czech Republic</option>';
	countrySelect+= '<option value="DK">Denmark</option>';
	countrySelect+= '<option value="DJ">Djibouti</option>';
	countrySelect+= '<option value="DM">Dominica</option>';
	countrySelect+= '<option value="DO">Dominican Republic</option>';
	countrySelect+= '<option value="EC">Ecuador</option>';
	countrySelect+= '<option value="EG">Egypt</option>';
	countrySelect+= '<option value="SV">El Salvador</option>';
	countrySelect+= '<option value="GQ">Equatorial Guinea</option>';
	countrySelect+= '<option value="ER">Eritrea</option>';
	countrySelect+= '<option value="EE">Estonia</option>';
	countrySelect+= '<option value="ET">Ethiopia</option>';
	countrySelect+= '<option value="FK">Falkland Islands (Malvinas)</option>';
	countrySelect+= '<option value="FO">Faroe Islands</option>';
	countrySelect+= '<option value="FJ">Fiji</option>';
	countrySelect+= '<option value="FI">Finland</option>';
	countrySelect+= '<option value="FR">France</option>';
	countrySelect+= '<option value="GF">French Guiana</option>';
	countrySelect+= '<option value="PF">French Polynesia</option>';
	countrySelect+= '<option value="TF">French Southern Territories</option>';
	countrySelect+= '<option value="GA">Gabon</option>';
	countrySelect+= '<option value="GM">Gambia</option>';
	countrySelect+= '<option value="GE">Georgia</option>';
	countrySelect+= '<option value="DE">Germany</option>';
	countrySelect+= '<option value="GH">Ghana</option>';
	countrySelect+= '<option value="GI">Gibraltar</option>';
	countrySelect+= '<option value="GR">Greece</option>';
	countrySelect+= '<option value="GL">Greenland</option>';
	countrySelect+= '<option value="GD">Grenada</option>';
	countrySelect+= '<option value="GP">Guadeloupe</option>';
	countrySelect+= '<option value="GU">Guam</option>';
	countrySelect+= '<option value="GT">Guatemala</option>';
	countrySelect+= '<option value="GG">Guernsey</option>';
	countrySelect+= '<option value="GN">Guinea</option>';
	countrySelect+= '<option value="GW">Guinea-Bissau</option>';
	countrySelect+= '<option value="GY">Guyana</option>';
	countrySelect+= '<option value="HT">Haiti</option>';
	countrySelect+= '<option value="HM">Heard Island and McDonald Islands</option>';
	countrySelect+= '<option value="VA">Holy See (Vatican City State)</option>';
	countrySelect+= '<option value="HN">Honduras</option>';
	countrySelect+= '<option value="HK">Hong Kong</option>';
	countrySelect+= '<option value="HU">Hungary</option>';
	countrySelect+= '<option value="IS">Iceland</option>';
	countrySelect+= '<option value="IN">India</option>';
	countrySelect+= '<option value="ID">Indonesia</option>';
	countrySelect+= '<option value="IR">Iran, Islamic Republic of</option>';
	countrySelect+= '<option value="IQ">Iraq</option>';
	countrySelect+= '<option value="IE">Ireland</option>';
	countrySelect+= '<option value="IM">Isle of Man</option>';
	countrySelect+= '<option value="IL">Israel</option>';
	countrySelect+= '<option value="IT">Italy</option>';
	countrySelect+= '<option value="JM">Jamaica</option>';
	countrySelect+= '<option value="JP">Japan</option>';
	countrySelect+= '<option value="JE">Jersey</option>';
	countrySelect+= '<option value="JO">Jordan</option>';
	countrySelect+= '<option value="KZ">Kazakhstan</option>';
	countrySelect+= '<option value="KE">Kenya</option>';
	countrySelect+= '<option value="KI">Kiribati</option>';
	countrySelect+= '<option value="KP">Korea, Democratic People\'s Republic of</option>';
	countrySelect+= '<option value="KR">Korea, Republic of</option>';
	countrySelect+= '<option value="KW">Kuwait</option>';
	countrySelect+= '<option value="KG">Kyrgyzstan</option>';
	countrySelect+= '<option value="LA">Lao People\'s Democratic Republic</option>';
	countrySelect+= '<option value="LV">Latvia</option>';
	countrySelect+= '<option value="LB">Lebanon</option>';
	countrySelect+= '<option value="LS">Lesotho</option>';
	countrySelect+= '<option value="LR">Liberia</option>';
	countrySelect+= '<option value="LY">Libya</option>';
	countrySelect+= '<option value="LI">Liechtenstein</option>';
	countrySelect+= '<option value="LT">Lithuania</option>';
	countrySelect+= '<option value="LU">Luxembourg</option>';
	countrySelect+= '<option value="MO">Macao</option>';
	countrySelect+= '<option value="MK">Macedonia, the former Yugoslav Republic of</option>';
	countrySelect+= '<option value="MG">Madagascar</option>';
	countrySelect+= '<option value="MW">Malawi</option>';
	countrySelect+= '<option value="MY">Malaysia</option>';
	countrySelect+= '<option value="MV">Maldives</option>';
	countrySelect+= '<option value="ML">Mali</option>';
	countrySelect+= '<option value="MT">Malta</option>';
	countrySelect+= '<option value="MH">Marshall Islands</option>';
	countrySelect+= '<option value="MQ">Martinique</option>';
	countrySelect+= '<option value="MR">Mauritania</option>';
	countrySelect+= '<option value="MU">Mauritius</option>';
	countrySelect+= '<option value="YT">Mayotte</option>';
	countrySelect+= '<option value="MX">Mexico</option>';
	countrySelect+= '<option value="FM">Micronesia, Federated States of</option>';
	countrySelect+= '<option value="MD">Moldova, Republic of</option>';
	countrySelect+= '<option value="MC">Monaco</option>';
	countrySelect+= '<option value="MN">Mongolia</option>';
	countrySelect+= '<option value="ME">Montenegro</option>';
	countrySelect+= '<option value="MS">Montserrat</option>';
	countrySelect+= '<option value="MA">Morocco</option>';
	countrySelect+= '<option value="MZ">Mozambique</option>';
	countrySelect+= '<option value="MM">Myanmar</option>';
	countrySelect+= '<option value="NA">Namibia</option>';
	countrySelect+= '<option value="NR">Nauru</option>';
	countrySelect+= '<option value="NP">Nepal</option>';
	countrySelect+= '<option value="NL">Netherlands</option>';
	countrySelect+= '<option value="NC">New Caledonia</option>';
	countrySelect+= '<option value="NZ">New Zealand</option>';
	countrySelect+= '<option value="NI">Nicaragua</option>';
	countrySelect+= '<option value="NE">Niger</option>';
	countrySelect+= '<option value="NG">Nigeria</option>';
	countrySelect+= '<option value="NU">Niue</option>';
	countrySelect+= '<option value="NF">Norfolk Island</option>';
	countrySelect+= '<option value="MP">Northern Mariana Islands</option>';
	countrySelect+= '<option value="NO">Norway</option>';
	countrySelect+= '<option value="OM">Oman</option>';
	countrySelect+= '<option value="PK">Pakistan</option>';
	countrySelect+= '<option value="PW">Palau</option>';
	countrySelect+= '<option value="PS">Palestinian Territory, Occupied</option>';
	countrySelect+= '<option value="PA">Panama</option>';
	countrySelect+= '<option value="PG">Papua New Guinea</option>';
	countrySelect+= '<option value="PY">Paraguay</option>';
	countrySelect+= '<option value="PE">Peru</option>';
	countrySelect+= '<option value="PH">Philippines</option>';
	countrySelect+= '<option value="PN">Pitcairn</option>';
	countrySelect+= '<option value="PL">Poland</option>';
	countrySelect+= '<option value="PT">Portugal</option>';
	countrySelect+= '<option value="PR">Puerto Rico</option>';
	countrySelect+= '<option value="QA">Qatar</option>';
	countrySelect+= '<option value="RE">Réunion</option>';
	countrySelect+= '<option value="RO">Romania</option>';
	countrySelect+= '<option value="RU">Russian Federation</option>';
	countrySelect+= '<option value="RW">Rwanda</option>';
	countrySelect+= '<option value="BL">Saint Barthélemy</option>';
	countrySelect+= '<option value="SH">Saint Helena, Ascension and Tristan da Cunha</option>';
	countrySelect+= '<option value="KN">Saint Kitts and Nevis</option>';
	countrySelect+= '<option value="LC">Saint Lucia</option>';
	countrySelect+= '<option value="MF">Saint Martin (French part)</option>';
	countrySelect+= '<option value="PM">Saint Pierre and Miquelon</option>';
	countrySelect+= '<option value="VC">Saint Vincent and the Grenadines</option>';
	countrySelect+= '<option value="WS">Samoa</option>';
	countrySelect+= '<option value="SM">San Marino</option>';
	countrySelect+= '<option value="ST">Sao Tome and Principe</option>';
	countrySelect+= '<option value="SA">Saudi Arabia</option>';
	countrySelect+= '<option value="SN">Senegal</option>';
	countrySelect+= '<option value="RS">Serbia</option>';
	countrySelect+= '<option value="SC">Seychelles</option>';
	countrySelect+= '<option value="SL">Sierra Leone</option>';
	countrySelect+= '<option value="SG">Singapore</option>';
	countrySelect+= '<option value="SX">Sint Maarten (Dutch part)</option>';
	countrySelect+= '<option value="SK">Slovakia</option>';
	countrySelect+= '<option value="SI">Slovenia</option>';
	countrySelect+= '<option value="SB">Solomon Islands</option>';
	countrySelect+= '<option value="SO">Somalia</option>';
	countrySelect+= '<option value="ZA">South Africa</option>';
	countrySelect+= '<option value="GS">South Georgia and the South Sandwich Islands</option>';
	countrySelect+= '<option value="SS">South Sudan</option>';
	countrySelect+= '<option value="ES">Spain</option>';
	countrySelect+= '<option value="LK">Sri Lanka</option>';
	countrySelect+= '<option value="SD">Sudan</option>';
	countrySelect+= '<option value="SR">Suriname</option>';
	countrySelect+= '<option value="SJ">Svalbard and Jan Mayen</option>';
	countrySelect+= '<option value="SZ">Swaziland</option>';
	countrySelect+= '<option value="SE">Sweden</option>';
	countrySelect+= '<option value="CH">Switzerland</option>';
	countrySelect+= '<option value="SY">Syrian Arab Republic</option>';
	countrySelect+= '<option value="TW">Taiwan, Province of China</option>';
	countrySelect+= '<option value="TJ">Tajikistan</option>';
	countrySelect+= '<option value="TZ">Tanzania, United Republic of</option>';
	countrySelect+= '<option value="TH">Thailand</option>';
	countrySelect+= '<option value="TL">Timor-Leste</option>';
	countrySelect+= '<option value="TG">Togo</option>';
	countrySelect+= '<option value="TK">Tokelau</option>';
	countrySelect+= '<option value="TO">Tonga</option>';
	countrySelect+= '<option value="TT">Trinidad and Tobago</option>';
	countrySelect+= '<option value="TN">Tunisia</option>';
	countrySelect+= '<option value="TR">Turkey</option>';
	countrySelect+= '<option value="TM">Turkmenistan</option>';
	countrySelect+= '<option value="TC">Turks and Caicos Islands</option>';
	countrySelect+= '<option value="TV">Tuvalu</option>';
	countrySelect+= '<option value="UG">Uganda</option>';
	countrySelect+= '<option value="UA">Ukraine</option>';
	countrySelect+= '<option value="AE">United Arab Emirates</option>';
	countrySelect+= '<option value="UK" selected>United Kingdom</option>';
	countrySelect+= '<option value="US">United States</option>';
	countrySelect+= '<option value="UM">United States Minor Outlying Islands</option>';
	countrySelect+= '<option value="UY">Uruguay</option>';
	countrySelect+= '<option value="UZ">Uzbekistan</option>';
	countrySelect+= '<option value="VU">Vanuatu</option>';
	countrySelect+= '<option value="VE">Venezuela, Bolivarian Republic of</option>';
	countrySelect+= '<option value="VN">Viet Nam</option>';
	countrySelect+= '<option value="VG">Virgin Islands, British</option>';
	countrySelect+= '<option value="VI">Virgin Islands, U.S.</option>';
	countrySelect+= '<option value="WF">Wallis and Futuna</option>';
	countrySelect+= '<option value="EH">Western Sahara</option>';
	countrySelect+= '<option value="YE">Yemen</option>';
	countrySelect+= '<option value="ZM">Zambia</option>';
	countrySelect+= '<option value="ZW">Zimbabwe</option>';
countrySelect+= '</select>';